# Generated by Django 4.2.30 on 2026-10-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_publisher_assigned_editors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Required. A valid email address.', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
